apiVersion: trainer.kubeflow.org/v1alpha1
kind: TrainJob
metadata:
  name: torchtitan-multinode-2
spec:
  trainer:
    numNodes: 2
    numProcPerNode: 4
    image: 633205212955.dkr.ecr.us-west-2.amazonaws.com/aws-dlc-base-ttt:latest
    command:
      - "bash"
      - "torchtitan-train-kfv2-dist.sh"
    env:
    - name: JOBSET_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.labels['jobset.sigs.k8s.io/jobset-name']
    - name: NCCL_DEBUG
      value: "INFO"
    # - name: PYTORCH_ALLOC_CONF
    #   value: "expandable_segments:True"
    # - name: CONFIG_FILE
    #   value: "./torchtitan/models/llama3/train_configs/debug_model.toml"
    # - name: TRAIN_FILE
    #   value: "torchtitan.train"
    - name: LOG_RANK
      value: "0"
    resourcesPerNode:
      requests:
        nvidia.com/gpu: 4
        vpc.amazonaws.com/efa: 1
      limits:
        nvidia.com/gpu: 4
        vpc.amazonaws.com/efa: 1
  runtimeRef:
    name: torch-distributed-torchtitan
    apiGroup: trainer.kubeflow.org
    kind: ClusterTrainingRuntime
