apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: nccl-tests-p6
spec:
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 20
  slotsPerWorker: 8
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
          restartPolicy: OnFailure
          containers:
          - image: 633205212955.dkr.ecr.us-west-2.amazonaws.com/nvcr-2503-efa-mg0140:latest
            imagePullPolicy: IfNotPresent
            name: test-nccl-launcher
            env:
             - name: PATH
               value: $PATH:/opt/amazon/efa/bin:/usr/bin
             - name: LD_LIBRARY_PATH
               value: /usr/local/cuda/lib64:/usr/local/cuda:/opt/amazon/efa/lib:/opt/amazon/openmpi/lib:$LD_LIBRARY_PATH
             - name: NCCL_DEBUG
               value: INFO
            #  - name: NCCL_SOCKET_IFNAME
            #    value: eth0
            #  - name: FI_PROVIDER
            #    value: efa
            #  - name: OFI_NCCL_PROTOCOL
            #    value: RDMA
            command:
            - /opt/amazon/openmpi/bin/mpirun
            - --allow-run-as-root
            - --tag-output
            - -np
            - "16"
            - -N
            - "8"
            - --bind-to
            - none
            - -x
            - PATH
            - -x
            - LD_LIBRARY_PATH
            - -x
            - NCCL_DEBUG=INFO
            - -x
            - NCCL_SOCKET_IFNAME=eth0
            - -x
            - FI_PROVIDER=efa
            - -x
            - OFI_NCCL_PROTOCOL=RDMA
            # - --mca
            # - plm_rsh_args
            # - "-p 2022"
            - --mca
            - pml
            - ^cm,ucx
            - --mca
            - btl
            - tcp,self
            - --mca
            - btl_tcp_if_exclude
            - lo,docker0,veth_def_agent
            - /usr/local/bin/alltoall_perf_mpi
            - -b
            - "8"
            - -e
            - "32G"
            - -f
            - "2"
            - -g
            - "1"
            - -c
            - "1"
            - -n
            - "100"
    Worker:
      replicas: 2
      template:
        spec:
          nodeSelector:
            node.kubernetes.io/instance-type: "p6-b200.48xlarge"
          containers:
          - image: 633205212955.dkr.ecr.us-west-2.amazonaws.com/nvcr-2503-efa-mg0140:latest
            imagePullPolicy: IfNotPresent
            name: nccl-tests-p6-worker
            volumeMounts:
            - name: shmem
              mountPath: /dev/shm
            resources:
              limits:
                nvidia.com/gpu: 8
                vpc.amazonaws.com/efa: 8
                memory: 32000Mi
              requests:
                nvidia.com/gpu: 8
                vpc.amazonaws.com/efa: 8
                memory: 32000Mi
          volumes:
          - name: shmem
            hostPath:
              path: /dev/shm